### BASIC 

In [2]:
import numpy as np 
print(np.__version__)

1.24.3


In [3]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [4]:
print(type(arr))

<class 'numpy.ndarray'>


### 0_D ARRAY

In [5]:
arr = np.array(42)

print(arr)

42


### 1_ D ARRAY 

In [6]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


### 2-D Arrays

In [7]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


### 3-D arrays

In [8]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


### Check Number of Dimensions?

In [9]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


### NUMPY FUNCTIONS 

In [11]:
np.zeros(3)  

array([0., 0., 0.])

In [12]:
np.ones(3)

array([1., 1., 1.])

In [13]:
np.empty(2)  # random num from memory

array([ 3.58610579e-092, -1.34935167e-243])

In [14]:
np.arange(3) # array with 3ELEMent

array([0, 1, 2])

In [15]:
np.arange(2,9,2) # start 2 with end 9 and your step =2  

array([2, 4, 6, 8])

In [16]:
# to create an array with values that are spaced linearly in a specified interval
np.linspace(0,10,num=5) 
# 0 -----> start 
# 10 -----> end 
# 5 ------num of numbers 

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [17]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)
b

array([0, 1, 2, 3])

In [18]:
c = a-b
c

array([20, 29, 38, 47])

In [19]:
b=b**2
b

array([0, 1, 4, 9])

In [20]:
10*np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [21]:
a<35

array([ True,  True, False, False])

In [22]:
A = np.array([[1, 1],
              [0, 1]])
B = np.array([[2, 0], 
              [3, 4]])
A * B    # elementwise product


array([[2, 0],
       [0, 4]])

In [23]:
A @ B # matrix product

array([[5, 4],
       [3, 4]])

In [24]:
A.dot(B) # another matrix product

array([[5, 4],
       [3, 4]])

In [25]:
a.sum(axis=0) 


140

In [27]:
b = np.arange(24).reshape(2,3,4) # 3d array
print(b)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [28]:
b.min(axis=1) # min of each row

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15]])

In [31]:

a

array([20, 30, 40, 50])

In [29]:
 a.ravel()        # returns the array, flattene

array([20, 30, 40, 50])

In [33]:
a.dtype

dtype('int32')

In [34]:
np.full((2,2),7)

array([[7, 7],
       [7, 7]])

In [35]:
np.eye(2)


array([[1., 0.],
       [0., 1.]])

In [36]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]],dtype=float)
arr.shape

(3, 3)

In [37]:
arr.ndim

2

In [38]:
arr.size

9

In [39]:
a = arr.astype('int')
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
c= np.array([1,2,3])
c


array([1, 2, 3])

In [41]:
c.max

<function ndarray.max>

In [42]:
c.min

<function ndarray.min>

In [43]:
b.sort()
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [44]:
arr = np.array([1.2, 2.3 , 4.5 , 6.7])
print (np.round(arr))

[1. 2. 4. 7.]


In [45]:
arr = np.array([1.2, 2.3 , 4.5 , 6.7])
print (np.ceil(arr))

[2. 3. 5. 7.]


In [46]:
arr = np.array([1.2, 2.3 , 4.5 , 6.7])
print (np.floor(arr))

[1. 2. 4. 6.]


In [47]:
#Statistical Operations
a = np.random.rand(10) 
a                          #Generate random numbers from a uniform distribution(0;1)

array([0.78878   , 0.4372948 , 0.8337523 , 0.11974427, 0.30135513,
       0.58373157, 0.10355552, 0.49830545, 0.47685898, 0.00246674])

In [48]:
b = np.random.randn(10)
b                              #: Generate random numbers from a normal distribution(1,-1)

array([ 1.84114507,  0.52819257, -0.22078647, -0.95800144,  0.69329704,
        0.55551432,  0.78461149, -0.66188007, -1.63630702, -0.9281947 ])

In [49]:
c=np.random.randint(30, size =10)
c#: Generate random integers.

array([19,  8, 13, 24,  3,  6,  6, 12, 20, 20])

In [50]:
d = a+b+c
d

array([21.62992507,  8.96548736, 13.61296583, 23.16174283,  3.99465217,
        7.13924589,  6.888167  , 11.83642538, 18.84055196, 19.07427204])

In [51]:
d.mean()  # Compute the mean of an array

13.514343553486176

In [52]:
np.median(d)           #Compute the median of an array

12.724695604154336

In [53]:
np.std(d)                  #Compute the standard deviation of an array.

6.456826738052835

In [54]:
np.var(d)                    # Compute the variance of an array.

41.69061152523402

In [55]:
#Linear Algebra
a = np.arange(12).reshape(4,3) # 2d array
print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [56]:
#Compute the inverse of a matrix
A = np.array([[4, 7], [2, 6]])
A_inv = np.linalg.inv(A)
print(A_inv)


[[ 0.6 -0.7]
 [-0.2  0.4]]


In [57]:
#Compute the determinant of a matrix
b = np.array([[1,3],[5,2]])
d_b=np.linalg.det(b)
d_b

-13.0

In [58]:
#Compute the eigenvalues and eigenvectors of a square 

C = np.array([[1, 2], [2, 4]])
eigenvalues, eigenvectors = np.linalg.eig(C)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:", eigenvectors)


Eigenvalues: [0. 5.]
Eigenvectors: [[-0.89442719 -0.4472136 ]
 [ 0.4472136  -0.89442719]]


In [59]:
arr = np.array([6,7,8])
np.insert(arr,0,12)

array([12,  6,  7,  8])

In [60]:
arr = np.array([1,2,3,4])
arr1 = np.array([5,6,7,8])
np.concatenate((arr,arr1))


array([1, 2, 3, 4, 5, 6, 7, 8])

In [61]:
arr = np.array([[1,2,3],[4,5,6]])
arr1 = np.array([4,5,6])
np.hsplit(arr,[1])
np.vsplit(arr,[1])

[array([[1, 2, 3]]), array([[4, 5, 6]])]

In [62]:
arr = np.append(arr,30)
arr  

array([ 1,  2,  3,  4,  5,  6, 30])

In [63]:
arr = np.delete(arr,[2])  ## delete 3
arr

array([ 1,  2,  4,  5,  6, 30])